[package]
name = "bitcoin_parser"
version = "0.1.0"
authors = ["Christopher Wolfram <chriscwolfram@gmail.com>"]
edition = "2018"


[dependencies]
chrono = "0.4"
rayon = "1.5"

serde_json = "1.0"
# indicatif = {version = "*", features = ["rayon"]}